FROM --platform=linux/amd64 node:16.20.2-alpine

WORKDIR /server
COPY server/package.json server/yarn.lock .env.server ./
RUN yarn install

COPY server .
RUN cp .env.server .env
RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start:prod" ]
