FROM --platform=linux/amd64 node:16.20.2-slim

WORKDIR /app
COPY admin/package.json admin/yarn.lock .env.admin ./
RUN yarn install

COPY admin .
RUN cp .env.admin .env
RUN yarn build

EXPOSE 5000

CMD [ "yarn", "start" ]
